// <auto-generated />
using Final_Project___Hope_Inman.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_Project___Hope_Inman.Migrations.AppDbContext2Migrations
{
    [DbContext(typeof(AppDbContext2))]
    partial class AppDbContext2ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final_Project___Hope_Inman.Module.Teams", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("baseball")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("basketball")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("football")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hockey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soccer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
